"""
loader.py — dag-factory loader for MWAA

Drop this file ONCE into your MWAA DAGs folder (S3 bucket/dags/).
It scans all dag_factory.yaml files committed by the SQL Deployment Portal
and registers the contained DAGs automatically.

Directory structure expected in the DAGs folder:
  dags/
    loader.py                          ← this file (manual one-time upload)
    team-a/
      schedules/
        dag_factory.yaml               ← auto-generated by portal
      views/
        customer_summary.sql           ← SQL files referenced by DAGs
      procedures/
        ...
    team-b/
      schedules/
        dag_factory.yaml
      ...

Requirements (add to MWAA requirements.txt):
  dag-factory>=0.19.0
  apache-airflow-providers-snowflake>=5.0.0
"""
import glob
import os

import dagfactory

# Find every dag_factory.yaml in all team schedule folders
_dag_root = os.path.dirname(os.path.abspath(__file__))
_yaml_files = glob.glob(os.path.join(_dag_root, "*/schedules/dag_factory.yaml"))

for _yaml_path in _yaml_files:
    try:
        _factory = dagfactory.DagFactory(_yaml_path)
        _factory.clean_dags(globals())
        _factory.generate_dags(globals())
    except Exception as _e:
        # Log but don't crash — a bad YAML shouldn't prevent other DAGs loading
        import logging
        logging.getLogger("loader").error("Failed to load %s: %s", _yaml_path, _e)
